// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6Deak8Kj0ZANgtQ5scPcNoYDdAAFyxo',
    appId: '1:837208654499:android:acecf7003eac37f058b516',
    messagingSenderId: '837208654499',
    projectId: 'smarthome-f8c0d',
    databaseURL: 'https://smarthome-f8c0d-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-f8c0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg0Yryei7FYSGEL11GYCKA4eavmP0UMZA',
    appId: '1:837208654499:ios:4397168b7f7bab2a58b516',
    messagingSenderId: '837208654499',
    projectId: 'smarthome-f8c0d',
    databaseURL: 'https://smarthome-f8c0d-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-f8c0d.appspot.com',
    iosClientId: '837208654499-k4tcthg4d782cf89a5c5rm48995mkugu.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartExtension',
  );
}
